# Generated by Django 3.1 on 2020-08-05 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sign_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='hospital',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='sign_app.hospital'),
        ),
    ]
