# Generated by Django 3.1 on 2020-08-05 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sign_app', '0002_patient_hospital'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='doctor',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='sign_app.doctor'),
        ),
    ]
