# Generated by Django 3.1 on 2020-08-10 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign_app', '0004_auto_20200806_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='contact_No',
            field=models.IntegerField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='h_contact',
            field=models.IntegerField(max_length=15, null=True),
        ),
    ]
