# Generated by Django 3.1 on 2020-08-10 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign_app', '0005_auto_20200810_1012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='contact_No',
        ),
        migrations.AddField(
            model_name='appointment',
            name='phone_number',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
