# Generated by Django 3.1 on 2020-08-10 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign_app', '0006_auto_20200810_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='h_contact',
            field=models.CharField(max_length=13, null=True),
        ),
    ]
