# Generated by Django 3.1 on 2020-08-10 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sign_app', '0007_auto_20200810_1155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicaltest',
            old_name='patient',
            new_name='patient_name',
        ),
        migrations.RemoveField(
            model_name='medicaltest',
            name='name',
        ),
    ]
