# Generated by Django 3.1 on 2020-08-10 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sign_app', '0008_auto_20200810_1328'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medical_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], default='M', max_length=1)),
                ('blood_group', models.CharField(choices=[('A+', 'A+ Type'), ('B+', 'B+ Type'), ('AB+', 'AB+ Type'), ('O+', 'O+ Type'), ('A-', 'A- Type'), ('B-', 'B- Type'), ('AB-', 'AB- Type'), ('O-', 'O- Type')], default='A+ Type', max_length=32)),
                ('patient_hist', models.CharField(choices=[('Asthma', 'Asthma'), ('Cancer', 'Cancer'), ('Cardiac disease', 'Cardiac disease'), ('Diabetes', 'Diabetes'), ('Hypertension', 'Hypertension'), ('Psychiatric disorder', 'Psychiatric disorder'), ('Epilepsy', 'Epilepsy')], default='Diabetes', max_length=32)),
                ('family_hist', models.CharField(choices=[('Asthma', 'Asthma'), ('Cancer', 'Cancer'), ('Cardiac disease', 'Cardiac disease'), ('Diabetes', 'Diabetes'), ('Hypertension', 'Hypertension'), ('Psychiatric disorder', 'Psychiatric disorder'), ('Epilepsy', 'Epilepsy')], default='Diabetes', max_length=32)),
                ('past_symptom', models.CharField(choices=[('Fever/Chills', 'Fever/Chills'), ('Unexplained change in weight', 'Unexplained change in weight'), ('Fatigue/Malaise/Generalized weakness', 'Fatigue/Malaise/Generalized weakness'), ('Headaches/Migraines', 'Headaches/Migraines'), ('Headaches/Migraines', 'Headaches/Migraines'), ('Dizziness', 'Dizziness'), ('Sinus Pain/Pressure/Discharge', 'Sinus Pain/Pressure/Discharge'), ('Excessive snoring', 'Excessive snoring'), ('Wheezing/Chronic Cough', 'Wheezing/Chronic Cough'), ('Shortness of breath', 'Shortness of breath'), ('Chest pain, pressure or tightness', 'Chest pain, pressure or tightness'), ('Swelling of hands/feet/ankles', 'Swelling of hands/feet/ankles'), ('Nausea/Vomiting', 'Nausea/Vomiting'), ('Abdominal pain', 'Abdominal pain'), ('Heartburn', 'Heartburn'), ('Constipation or diarrhea', 'Constipation or diarrhea'), ('Stiffness/Pain in joints/muscles', 'Stiffness/Pain in joints/muscles'), ('Joint swelling', 'Joint swelling'), ('Bleeding/Easy bruising', 'Bleeding/Easy bruising'), ('Excessive urination', 'Excessive urination'), ('Excessive thirst/hunger', 'Excessive thirst/hunger'), ('Hot flashes', 'Hot flashes'), ('Painful/Bloody urination', 'Painful/Bloody urination'), ('Difficulty urinating/Night-time urination', 'Difficulty urinating/Night-time urination'), ('Urinary incontinence (leakage)', 'Urinary incontinence (leakage)'), ('Sexual Difficulties/Painful intercourse', 'Sexual Difficulties/Painful intercourse'), ('Rash', 'Rash'), ('Anxiety/Panic Attacks', 'Anxiety/Panic Attacks'), ('Concentration Difficulty', 'Concentration Difficulty'), ('Insomnia/Problems with Sleep', 'Insomnia/Problems with Sleep'), ('Loss of energy', 'Loss of energy'), ('Thoughts of harming self or others', 'Thoughts of harming self or others')], default='Fever', max_length=50)),
                ('ongoing_medication', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')])),
                ('medication_allergy', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')])),
                ('tobacco_history', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')])),
                ('alcohol_consumption', models.CharField(choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Occasionally', 'Occasionally'), ('Never', 'Never')], default='Daily', max_length=32)),
            ],
        ),
        migrations.AlterField(
            model_name='medicaltest',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docs', to='sign_app.doctor'),
        ),
    ]
