# Generated by Django 3.1 on 2020-08-12 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign_app', '0009_auto_20200810_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('conformed', 'conformed'), ('pending', 'pending')], max_length=200, null=True),
        ),
    ]
